### ISSUE TITLE
Send binary abi to sign function

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [EOSIO/eosjs2#42]
Send binary abi to sign function so the integrity of the abi can be verified against the chain.

**Comment by randytorres** [comment]
@jeffreyssmith2nd @tbfleming Can you share more details on this?

**Comment by tbfleming** [comment]
```
export interface SignatureProviderArgs {
  chainId: string;
  requiredKeys: string[];
  serializedTransaction: Uint8Array;
  abis: GetAbiResult[];
}
```

The abis are in JSON format right now. The need to switch to binary format.

**Comment by chris-allnutt** [comment]
Instead of deserializing the binary abi to json just send it thru as binary since we can hash

**Comment by randytorres** [comment]
#52
