### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [EOSIO/eosjs2#44]
Add unit testing where appropriate.

- [x] api
- [x] jsonrpc
- [x] jssig
- [x] serialize (?)
- [x] numeric (?)

Note:
* Serialization is tested in the against abieos in the [abieos repo](https://github.com/EOSIO/abieos)

**Comment by randytorres** [comment]
I'm going to start writing tests for eosj2-api.ts

**Comment by esheffield** [comment]
I'll pick up eosjs2-jsonrpc.ts

**Comment by tbfleming** [comment]
numeric is covered by abieos's tests also.

**Comment by randytorres** [comment]
@tbfleming just to confirm, numeric and serialize files are both covered by tests in abieos?

**Comment by tbfleming** [comment]
@randytorres yes

**Comment by randytorres** [comment]
api tests were merged in #50
