### ISSUE TITLE
ReferenceError: 'Proxy' is undefined in IE11

### ISSUE THREAD

**Issue by terrylks** [EOSIO/eosjs2#76]
To @chris-allnutt and refer to #56 
An error `ReferenceError: 'Proxy' is undefined` will appear while using eosjs in IE11. We could reproduce this error in the simple boilerplate project:

Reproducing steps:
Clone repo https://github.com/EOSIO/eosio-project-boilerplate-simple and run ./quick_start.sh
Open http://localhost:3000/ in IE11
Add a note by using the first account in the listed account array.
Then you could see the error in the console and the note is not added to the blockchain.

FYI:
By looking into the source code of eosjs, the `Proxy` object is used in `/src/ripemd.js` line 382.
The `ripemd` is required from `/src/eosjs-numeric.ts`.

And `Proxy` is not supported in IE11 at all.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

@ChristianDunst @rickykung

**Comment by chris-allnutt** [comment]
Thanks, @terrylks I'll look into this.

**Comment by chris-allnutt** [comment]
@tbfleming would it be possible to replace our RipeMD with a package like this one? https://github.com/crypto-browserify/ripemd160/blob/master/index.js

Or update our RipeMD to not utilize Proxy. It looks like it's only used in one place and I'm pretty sure we could make it work without the Proxy.

**Comment by jeffreyssmith2nd** [comment]
I think the above message was for @tbfleming

**Comment by tbfleming** [comment]
The above package depends on Node's Buffer. eosjs avoids pulling in Node stuff.

**Comment by terrylks** [comment]
@tbfleming Any update on this?

cc: @chris-allnutt @ChristianDunst @rickykung @andriantolie

**Comment by tbfleming** [comment]
It looks like to fix it, someone will have to figure out what that code is using Proxy for and rewrite it to not use Proxy. No one is currently assigned.

**Comment by chris-allnutt** [comment]
The respective lines are as follow @tbfleming 

https://github.com/EOSIO/eosjs2/blob/master/src/ripemd.js#L382
https://github.com/EOSIO/eosjs2/blob/master/src/ripemd.es5.js#L331

@terrylks @ChristianDunst @rickykung @andriantolie  would you like to propose a PR for this?

**Comment by terrylks** [comment]
@chris-allnutt @tbfleming 
I have made a PR for the fix in eosjs repo: https://github.com/EOSIO/eosjs/pull/411
Please check. Thanks.
